package:
  name: flaapluc
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/jlenain/flaapluc.git
  
requirements:
  build:
    - python 2.7*
    - astropy
    - matplotlib
    - ephem
run:
    - python

about:
  home: https://github.com/jlenain/flaapluc
  license: BSD
  license_file: LICENSE
